name: polymer_autonotify
version: 1.0.0-rc.10+1
author: Vittorio Ballestra (Drafintech s.r.l.) <vittorio.ballestra@gmail.com>
description: auto notify support for Polymer 1.0
homepage : https://github.com/dam0vm3nt/polymer_autonotify
environment:
 sdk: ">=1.8.0 <2.0.0"

dependencies:
 polymer: ">=1.0.0-rc.8"

dev_dependencies:
 autonotify_observe: "^1.0.0"
 test: any

transformers:
- autonotify_observe:
   entry_points:
    - test/autonotify_test.html
- test/pub_serve:
   $include: test/**_test{.*,}.dart

# Comment befor publish
#dependency_overrides:
# autonotify_observe:
#  path: ../autonotify_observe
