name: polymer_autonotify
version: 0.0.3-SNAPSHOT
author: Vittorio Ballestra (Drafintech s.r.l.) <vittorio.ballestra@gmail.com>
description: auto notify support for Polymer 1.0
homepage : https://github.com/dam0vm3nt/polymer_autonotify
sdk: ">=1.8.0 <2.0.0"

dependencies:
 polymer: ">=1.0.0 <2.0.0"
 observe: any
 barback: any

#dependency_overrides:
#  polymer:
#    git:
#      ref: behaviors
#      url: https://github.com/dart-lang/polymer-dart.git
#  polymer_interop:
#    git:
#      ref: 0.2.0-dev
#      url: https://github.com/dart-lang/polymer_interop.git

