name: demo_polymer_autonotify
description: Demo project for polymer autonotify
version: 0.0.1
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
homepage: https://github.com/dam0vm3nt/polymer_autonotify
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
 polymer_elements: ">=1.0.0-rc.3"
 autonotify_observe: "^1.0.0-rc.10"

dependency_overrides:
 polymer_autonotify:
  path: ..
 autonotify_observe:
  path: ../../autonotify_observe


transformers:
- autonotify_observe:
    entry_points:
    - web/index.html
